name: AutoSort
version: '@mod_version@'
main: lol.hub.autosort.Plugin
api-version: '1.21'
author: nothub
description: Tidy up them containers
website: https://github.com/nothub/AutoSort

commands:
  autosort:
    description: 'Toggle container sorting'
    usage: '/autosort'
    aliases: [ 'sort' ]
    permission: autosort.toggle

permissions:
  autosort.toggle:
    default: true
