name: 'AutoSort'
version: '@mod_version@'
api-version: '@minecraft_version@'
main: 'lol.hub.autosort.Plugin'
description: 'Tidy up them containers'
website: 'https://github.com/nothub/AutoSort'
authors: [ 'nothub' ]
contributors: [ ]

commands:
  autosort:
    description: 'Toggle container sorting'
    usage: '/autosort'
    aliases: [ 'sort' ]
    permission: autosort.toggle

permissions:
  autosort.toggle:
    default: true
